### ISSUE TITLE
Look into mapbox api

### ISSUE THREAD

**Issue by Greeny467** [Greeny467/date-planning-project-website#1]

**Comment by NateGreeff** [comment]
Documentation - https://docs.mapbox.com/api/search/search-box/

**Comment by NateGreeff** [comment]
Playground - https://docs.mapbox.com/playground/search-box/

**Comment by NateGreeff** [comment]
pk.eyJ1IjoibmF0aGFuZzQ1NiIsImEiOiJjbGtqNDg0a2YwMzQ5M2RvOGx6dGgxb3FkIn0.yUbT_dC_9GY3u3-rryFFeA
